### ISSUE TITLE
Secret to Environment Variable 

### ISSUE THREAD

**Issue by initharrington** [release-argus/Helm#3]
Hello,

I am trying to use a k8s secret into an env variable that argus will use in the config.  It does not appear to be working.

I setup a secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: argus-secrets
type: Opaque
data:
  GITHUB_API_KEY: $GITHUB_API_KEY
```

Passed in the Secret to the values file:
```
  # List of Secrets to use as env var
  extraSecretEnvironmentVars:
    - name: GITHUB_API_KEY
      valueFrom:
        secretKeyRef:
          name: argus-secrets
          key: GITHUB_API_KEY
```

Setup the config to use the environment variable:
```
  config: |
    service:
      app[argus]:
        latest_version:
          type: github
          access_token: $GITHUB_API_KEY
          url: release-argus/argus
        deployed_version:
          url: http://localhost:8080/api/v1/version
          json: version
        dashboard:
          icon: https://github.com/release-argus/Argus/raw/master/web/ui/static/favicon.svg
          web_url: https://github.com/release-argus/Argus/blob/master/CHANGELOG.md
 ```
 
 The secret is in the container:
```# env | grep GITHUB
GITHUB_API_KEY=REDACTED
```

The logs say I have an invalid token:
```
ERROR: app[argus], github access token is invalid
ERROR: app[argus], tag_name not found at release-argus/argus
```

When I put the API key in the values file directly, it works, but that is not something I will do.
Does Argus config process env variables or do I have something setup wrong?

Thanks
